version: '3.1'

services: 
    app:
        build: .
        container_name: keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_ADDR=db
            - DB_VENDOR=mysql
            - DB_DATABASE=keycloak
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=root
        ports:
            - 8080:8080
        depends_on:
            - db

    db:
        image: mysql
        container_name: keycloak_mysql
        restart: always
        tty: true
        ports: 
            - 3306:3306
        volumes: 
            - ./.docker/db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=keycloak
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_USER=root

